Do not pass boost functions to abstract server to (de)activate costmaps
naturerobots/move_base_flex pull request #142
Opened 2019-06-23 19:19 UTC by corot

Run instead abstract methods (possibly) overridden in the costmap server
To do this I have refactored all costmap-related handling to a new CostmapWrapper class
In the process, I have also added/fixed many missing/wrong comments

This PR is an evolution of #141, so if merged, #141 can be discarded

2019-06-24 09:07 UTC, spuetz requested changes
We need to keep the API for two version changes.

2019-06-24 09:36 UTC, corot commented on mbf_abstract_nav/src/abstract_controller_execution.cpp
> +        if (!safetyCheck())
I'm replicating the behavior of old-good move_base: assume is a temporal condition and publish zero velocity meanwhile. That makes sense, cause transitory problems like a laser not publishing for a second will just delay, but not cancel, the navigation

2019-06-24 09:38 UTC, spuetz commented on mbf_abstract_nav/src/abstract_controller_execution.cpp
> +        if (!safetyCheck())
Maybe then we should return an outcome code by the `safetyCheck` function and decide weather to stop or not.

2019-06-24 09:46 UTC, corot commented on mbf_abstract_nav/src/abstract_controller_execution.cpp
> +        if (!safetyCheck())
Not sure, cause the code is provided by the underlying specific implementation (we need a better name for this), and so the abstract level won't know anything about those codes (e.g. OUTDATED_COSTMAP)

2019-06-24 09:48 UTC, spuetz commented on mbf_abstract_nav/src/abstract_controller_execution.cpp
> +        if (!safetyCheck())
We simply could use the outcome codes defined in the action. less or equal 10 => success code >10 => failure code.

2019-06-24 10:27 UTC, corot commented on mbf_abstract_nav/src/abstract_controller_execution.cpp
> +        if (!safetyCheck())
makes sense

2019-06-25 08:39 UTC, spuetz commented
I tested it: It works fine.

2019-06-25 10:54 UTC, merged