Feature/verbose
naturerobots/move_base_flex pull request #159
Opened 2019-10-02 14:49 UTC by spuetz

Add verbose messages and outcome codes.

2019-10-16 08:39 UTC, spuetz commented
@corot Any change requests?

2019-10-17 18:32 UTC, corot reviewed
Lgtm, but I have some minor comments

2019-10-28 10:54 UTC, spuetz commented on mbf_utility/include/mbf_utility/exe_path_exception.h
> +#ifndef MBF_UTILITY__EXE_PATH_EXCEPTION_H_
Japp

2019-10-28 10:54 UTC, spuetz commented on mbf_msgs/action/Recovery.action
> +uint8 STOPPED         = 157
Japp

2019-10-28 10:55 UTC, spuetz commented on mbf_abstract_nav/src/abstract_planner_execution.cpp
> +          ROS_INFO_STREAM("planning execution time for " << name_ << ": " <<  (m2 - m1).toSec());
Japp :D

2019-10-28 11:03 UTC, spuetz commented on mbf_abstract_nav/src/recovery_action.cpp
> -            execution.stop();
Then we need to implement the cancel method in the corresponding plugins. interrupting the thread could lead in unpredictable behaviour. Stopping / interrupting also only works if there is an interruption point in the corresponding plugin.

2019-10-28 18:56 UTC, corot commented on mbf_abstract_nav/src/recovery_action.cpp
> -            execution.stop();
But most old plugins don't implement cancel....  And this abrupt stop is only for cases when the controller/planner/recovery takes too long (isPatienceExceeded() == true), so probably they go stuck somewhere. So I would retain the stop(), if possible making it safer.

2020-02-04 11:16 UTC, spuetz commented on mbf_abstract_nav/src/recovery_action.cpp
> -            execution.stop();
They also only work if there are interruption points in the plugins, again: unpredictable behaviour. And if patience is exceeded then the plugin is not called again. If we want the system to stop immediately, we have to implement the cancel method in these plugins.

2020-02-04 15:08 UTC, corot commented on mbf_abstract_nav/src/recovery_action.cpp
> -            execution.stop();
:thinking:  not sure about this... so I follow you opinion

2020-02-04 15:11 UTC, corot commented on mbf_msgs/action/Recovery.action
> +uint8 STOPPED         = 157
so...???

2020-02-04 15:11 UTC, corot commented on mbf_utility/include/mbf_utility/exe_path_exception.h
> +#ifndef MBF_UTILITY__EXE_PATH_EXCEPTION_H_
so...???

2020-02-04 15:12 UTC, corot commented on mbf_abstract_nav/src/abstract_planner_execution.cpp
> +          ROS_INFO_STREAM("planning execution time for " << name_ << ": " <<  (m2 - m1).toSec());
so...???

2020-02-15 02:16 UTC, corot requested changes
looks good, but I found some issues

2020-02-15 02:16 UTC, corot commented on mbf_abstract_nav/src/controller_action.cpp
> -          // Note that this is not the same situation as in case AbstractControllerExecution::PAT_EXCEEDED,
This part of the comment is still valuable, imho, as it can be confusing the two different cases of patience exceeded

2020-02-15 02:16 UTC, corot commented on mbf_abstract_nav/src/controller_action.cpp
> +          ROS_INFO_STREAM_THROTTLE_NAMED(3, name_, "The controller patience has been exceeded! Wait for it to finish the current run.");
Move to isPatienceExceeded, see comment there

2020-02-15 02:16 UTC, corot commented on mbf_abstract_nav/src/abstract_execution_base.cpp
> +  ROS_WARN_STREAM("Try to stop the move base flex plugin \"" << name_ << "\" rigorously by interrupting the thread!");
No "the move base flex plugin", just "plugin"

2020-02-15 02:16 UTC, corot commented on mbf_abstract_nav/src/abstract_planner_execution.cpp
> +  if(cost_ < 1e-7 && !plan_.empty())
:question:

2020-02-15 02:16 UTC, corot commented on mbf_abstract_nav/src/abstract_planner_execution.cpp
> +        ROS_DEBUG_STREAM("planning execution time for " << name_ << ": " <<  (m2 - m1).toSec());
I think this should be done within the planners, when needed

2020-02-15 02:16 UTC, corot commented on mbf_abstract_nav/src/recovery_action.cpp
> +            ROS_WARN_STREAM("Cancel recovering \"" << goal.behavior << "\" failed or not supported; maybe wait until it is finished!");
recovery behavior,  to be consistent

2020-02-15 02:16 UTC, corot commented on mbf_msgs/action/ExePath.action
> +uint8 STOPPED         = 115
Add comment as in planner?
Also, I like STOPPED as the last code,  just personal preference

2020-02-15 02:16 UTC, corot commented on mbf_msgs/action/ExePath.action
> +uint8 MAP_ERROR       = 117
maybe some comment here?  What does it mean?

2020-03-24 16:14 UTC, spuetz commented on mbf_abstract_nav/src/abstract_controller_execution.cpp
> +    if(ros::Time::now() - last_valid_cmd_time_ > patience_)
This is the behaviour of `move_base`. See https://github.com/ros-planning/navigation/blob/0d0cc703528f657931deccb1a3488cddea10a604/move_base/src/move_base.cpp#L903
and https://github.com/ros-planning/navigation/blob/0d0cc703528f657931deccb1a3488cddea10a604/move_base/src/move_base.cpp#L911

2020-03-25 00:38 UTC, corot commented on mbf_abstract_nav/src/abstract_controller_execution.cpp
> +    if(ros::Time::now() - last_valid_cmd_time_ > patience_)
mmm... u are right

2020-03-25 00:47 UTC, corot requested changes
Almost done, but there still some minor comments open

2020-03-25 00:51 UTC, corot commented on mbf_msgs/action/GetPath.action
> +uint8 MAP_ERROR       = 63
Can we reorder as in ExePath.action ?

2020-03-26 15:18 UTC, corot approved these changes
lgtm

2020-03-26 16:01 UTC, merged