add parameter to actively stop once the goal is reached
naturerobots/move_base_flex pull request #166
Opened 2019-12-26 03:31 UTC by ChristofDubs

Related to Issue #109, the current implementation (correct me if I'm wrong) requires one to delegate the responsibility to stop the robot to the local planner. If someone wanted to ensure that the robot stopped at a goal, one would have to do the following:
- The local planner has to return false for `isGoalReached()` if the robot isn't stopped yet (i.e. if last call to `computeVelocityCmd()` did not set `cmd_vel` to zero)
- `mbf_tolerance_check_` needs to be false (otherwise above doesn't work)
- You can probably not use multiple local planners, because this method relies on the planner's last internally calculated velocity command being the last one that was published by move_base_flex

This is not very nice; as the thread in the issue suggests, this should be handled by a configurable parameter.

I verified on my system that adding these changes stops the robot at the goal (by modifying the local planner to return non-zero commands in all cases)

2020-01-14 09:36 UTC, corot commented
Makes sense. And code lgtm. Maybe rename "stop_at_goal" as "force_stop_at_goal"?  Cause "stop_at_goal" sounds like if false, the robot won't stop!

2020-01-14 10:07 UTC, spuetz requested changes

2020-01-14 10:07 UTC, spuetz commented on mbf_abstract_nav/src/abstract_controller_execution.cpp
> +    private_nh.param("stop_at_goal", stop_at_goal_, true);
change default to `false`

2020-01-15 02:22 UTC, ChristofDubs commented
> Also I would change default to false, so current behavior doesn't change unless actively setting the new param.

I get the point of not changing the current behavior. The reason I picked `true` as default was that I think this is more close to the default behavior a (new) user would expect, also the described advanced use-case to not publish a zero velocity command to "roll through waypoints" seems like a workaround to me for a via_points feature (which the mentioned TEB local planner actually already supports).

Anyway I changed the default to `false`, you can merge it like that, otherwise let me know and I'd be happy to revert back the change.

2020-01-15 12:28 UTC, merged

2020-01-15 12:28 UTC, corot commented
Thanks!