Move RobotInformation to mbf_utility, as it can be used generally
naturerobots/move_base_flex pull request #196
Opened 2020-06-09 11:27 UTC by corot

I also fixed some clang-tidy warnings in the process

2020-06-11 19:42 UTC, Bitfroest commented on mbf_abstract_nav/include/mbf_abstract_nav/abstract_controller_execution.h
> -        const std::string name,
format of `const std::string& name`

Note that parameter 'name' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions clang-tidy

2020-06-11 19:44 UTC, Bitfroest commented on mbf_abstract_nav/include/mbf_abstract_nav/abstract_execution_base.h
> +#include <mbf_abstract_nav/MoveBaseFlexConfig.h>
`#include "mbf_abstract_nav/MoveBaseFlexConfig.h"`

prefers the workspace version more than the apt package

2020-06-11 19:45 UTC, Bitfroest commented on mbf_abstract_nav/include/mbf_abstract_nav/abstract_controller_execution.h
> -        const std::string name,
Seems to be different throughout files, do you use a clang-format or something?

2020-06-11 19:47 UTC, Bitfroest commented on mbf_abstract_nav/include/mbf_abstract_nav/recovery_action.h
> +#include <mbf_utility/robot_information.h>
`#include "mbf_utility/robot_information.h"`

2020-06-12 09:49 UTC, spuetz requested changes
Can you separate the style changes from the logic changes. Meaning two PRs.

2020-06-15 00:47 UTC, corot commented
> Can you separate the style changes from the logic changes. Meaning two PRs.

Mostly done

2020-06-18 11:49 UTC, spuetz commented
LGTM

2020-06-18 11:49 UTC, merged