Do not call isGoalReached on controller when mbf_tolerance_check parameter is true
naturerobots/move_base_flex pull request #206
Opened 2020-07-04 09:23 UTC by corot

So we check if we have arrived instead of asking the controller. Current code considers that we have arrived when EITHER the controller or MBF consider that we have arrived, what is much less useful and confusing. You cannot, for example, enforce a higher precission than usual without calling controller dynamic reconfigure (assuming it has). 

I also rename `mbf_tolerance_check` as `check_goal_reached`, as we are checking if we have arrived, independently of tolerances.

2020-09-16 10:23 UTC, spuetz commented
Hmmm this is now used in several projects... I would prefer to keep the name.

2020-09-17 07:13 UTC, corot commented
> Hmmm this is now used in several projects... I would prefer to keep the name.

Keep issue #213 in mind... if using this parameter, you can finish way off of the goal, as we are not checking if the robot is stopped at the goal. I'm mostly in favor of removing this feature entirely.

2020-10-01 03:32 UTC, corot commented
> Hmmm this is now used in several projects... I would prefer to keep the name.

Yup, that's why we do for noetic

2020-10-14 16:36 UTC, spuetz requested changes

2020-10-15 16:03 UTC, merged