Fixes leaking of threads in abstract_action.
naturerobots/move_base_flex pull request #88
Opened 2018-09-24 15:37 UTC by howardcochran

There is no convenient place for anyone to join() the wrapper thread which
runs runAndCleanup(), so make the thread detach itself just before exiting.

Fixes #87 "get_path and exe_path actions leak a thread every invocation"

2018-09-26 09:09 UTC, spuetz approved these changes

2018-09-26 09:10 UTC, corot approved these changes

2018-09-26 09:25 UTC, spuetz requested changes
Thank you for finding the problem and the Pull Request.

2018-09-26 09:27 UTC, spuetz commented on mbf_abstract_nav/include/mbf_abstract_nav/abstract_action.h
> +    self->detach();
The destructor also calls the `detach()` method.

2018-10-02 07:47 UTC, corot commented
I remake the PR on #91; instead of threads, we are leaking memory due to not destroyed threads. Thanks @howardcochran a lot for pointing us to the problem

2018-10-02 07:47 UTC, closed without merging