Feature add outcome to feedback
naturerobots/move_base_flex pull request #89
Opened 2018-09-24 16:08 UTC by howardcochran

Implements #77 "Improvements to ExePathFeedback
(and MoveBaseFeedback)"

2018-09-26 09:42 UTC, spuetz requested changes

2018-09-26 09:42 UTC, spuetz commented on mbf_abstract_nav/src/recovery_action.cpp
> +        if (result.message.size() == 0)
if(result.message.empty())

2018-09-26 09:42 UTC, spuetz commented on mbf_abstract_nav/include/mbf_abstract_nav/controller_action.h
> +  void fillExePathFeedback(
Better call it `publishExePathFeedback()` and use the `goal_handle` as parameter.

2018-10-02 20:28 UTC, spuetz commented
@howardcochran Would be cool if you do the changes I've suggested. After that we could merge that. :)

2018-10-04 02:27 UTC, howardcochran commented
Thanks for the feedback, @spuetz.  I have rewritten the commits with the requested changes and rebased the branch on 0.2.1.

2018-10-08 22:18 UTC, merged